{
  "escalation_message": null,
  "message": "## Description:\n Internal MySQL backup verification failed <%= cloudops_non_critical_pagerduty %>.  \n\n## Escalation Path:\n\n## Possible Causes:\n Backup is broken and failed to be test restored.\n Backup is older than 30 hours.\n## Potential Solutions:\n\n Verify backup job has actually been running.\n Verify backup is present in backup location.\n Verify backup can be restored and accessed. \n\n##Feedback:\n Have feedback for this alert? [File an issue](https://github.com/pivotal-cf/datadog-config/issues/new)",
  "name": "<%= environment %>: Internal MySQL backup failed verification",
  "no_data_timeframe": 480,
  "notify_audit": false,
  "notify_no_data": true,
  "query": "min(last_4h):avg:cloudops_tools.mysql_backup.success{environment:<%= environment %>} < 1",
  "renotify_interval": 0,
  "timeout_h": 0
}
